module.exports = (sequelize, DataTypes) => {
    const AccountPerformanceReportRequest = sequelize.define('AccountPerformance', {
        Account_Id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        AccountId: {type: DataTypes.INTEGER,allowNull: true, allowNull: true},
        AccountName: {type: DataTypes.STRING,allowNull: true, allowNull: true},
        AccountNumber: {type: DataTypes.STRING,allowNull: true, allowNull: true},
        AccountStatus: {type: DataTypes.STRING,allowNull: true},
        AdDistribution: {type: DataTypes.STRING,allowNull: true},
        Assists: {type: DataTypes.INTEGER,allowNull: true},
        AverageCpc : {type: DataTypes.FLOAT,allowNull: true},
        AverageCpp: {type: DataTypes.STRING,allowNull: true},
        AveragePosition: {type: DataTypes.FLOAT,allowNull: true},
        //BidMatchType: {type: DataTypes.STRING}  ,
        ClickCalls : {type: DataTypes.INTEGER,allowNull: true},
        Clicks: {type: DataTypes.INTEGER,allowNull: true},
        ConversionRate : {type: DataTypes.STRING,allowNull: true},
        Conversions : {type: DataTypes.INTEGER,allowNull: true},
        CostPerAssist : {type: DataTypes.STRING,allowNull: true},
        CostPerConversion : {type: DataTypes.FLOAT,allowNull: true},
        Ctr : {type: DataTypes.STRING,allowNull: true},
        CurrencyCode: {type: DataTypes.STRING,allowNull: true},
        DeliveredMatchType : {type: DataTypes.STRING,allowNull: true},
        //DeviceOS: {type: DataTypes.STRING,allowNull: true},
        DeviceType: {type: DataTypes.STRING,allowNull: true},
        ExactMatchImpressionSharePercent: {type: DataTypes.STRING,allowNull: true},
        /*ImpressionLostToAdRelevancePercent: {type: DataTypes.STRING,allowNull: true},
        ImpressionLostToBidPercent: {type: DataTypes.STRING,allowNull: true},
        ImpressionLostToBudgetPercent: {type: DataTypes.STRING,allowNull: true},
        ImpressionLostToExpectedCtrPercent: {type: DataTypes.STRING,allowNull: true},
        ImpressionLostToRankPercent: {type: DataTypes.STRING,allowNull: true},*/
        Impressions: {type: DataTypes.INTEGER,allowNull: true},
        //ImpressionSharePercent : {type: DataTypes.STRING,allowNull: true},
        LowQualityClicks : {type: DataTypes.INTEGER,allowNull: true},
        LowQualityClicksPercent : {type: DataTypes.STRING,allowNull: true},
        LowQualityConversionRate : {type: DataTypes.STRING,allowNull: true},
        LowQualityConversions : {type: DataTypes.INTEGER,allowNull: true},
        LowQualityGeneralClicks: {type: DataTypes.INTEGER,allowNull: true},
        LowQualityImpressions : {type: DataTypes.INTEGER,allowNull: true},
        LowQualityImpressionsPercent : {type: DataTypes.STRING,allowNull: true},
        LowQualitySophisticatedClicks: {type: DataTypes.STRING,allowNull: true},
        ManualCalls : {type: DataTypes.INTEGER,allowNull: true},
        Network: {type: DataTypes.STRING,allowNull: true},
        PhoneCalls : {type: DataTypes.INTEGER,allowNull: true},
        PhoneImpressions : {type: DataTypes.INTEGER,allowNull: true},
        Ptr : {type: DataTypes.STRING,allowNull: true},
        ReturnOnAdSpend : {type: DataTypes.FLOAT,allowNull: true},
        Revenue: {type: DataTypes.FLOAT,allowNull: true},
        RevenuePerAssist : {type: DataTypes.STRING,allowNull: true},
        RevenuePerConversion : {type: DataTypes.FLOAT,allowNull: true},
        Spend : {type: DataTypes.FLOAT,allowNull: true},
        TimePeriod : {type: DataTypes.STRING,allowNull: true}
    }, { freezeTableName: true });
    AccountPerformanceReportRequest.associate = models => {}
    return AccountPerformanceReportRequest;
};