module.exports = (sequelize, DataTypes) => {
    const AdPerformanceReportRequest = sequelize.define('AdPerformance', {
        Ad_Id: {
            type: DataTypes.INTEGER,
            autoIncrement: true,
            primaryKey: true
        },
        AdId: {type: DataTypes.INTEGER},
        AccountId : {type: DataTypes.INTEGER} ,
        AccountName : {type: DataTypes.STRING} ,
        AccountNumber : {type: DataTypes.STRING} ,
        AccountStatus : {type: DataTypes.STRING} ,
        AdDescription : {type: DataTypes.STRING},
        AdDistribution : {type: DataTypes.STRING} ,
        AdGroupId : {type: DataTypes.INTEGER} ,
        AdGroupName : {type: DataTypes.STRING} ,
        AdGroupStatus : {type: DataTypes.STRING} ,
        AdLabels : {type: DataTypes.STRING},
        AdStatus : {type: DataTypes.STRING} ,
        AdTitle : {type: DataTypes.STRING} ,
        AdType : {type: DataTypes.STRING} ,
        Assists : {type: DataTypes.INTEGER} ,
        AverageCpc : {type: DataTypes.FLOAT} ,
        AveragePosition : {type: DataTypes.FLOAT} ,
        BidMatchType : {type: DataTypes.STRING} ,
        BusinessName : {type: DataTypes.STRING} ,
        CampaignId : {type: DataTypes.INTEGER} ,
        CampaignName : {type: DataTypes.STRING} ,
        CampaignStatus : {type: DataTypes.STRING} ,
        Clicks : {type: DataTypes.INTEGER} ,
        ConversionRate : {type: DataTypes.STRING} ,
        Conversions : {type: DataTypes.INTEGER} ,
        CostPerAssist : {type: DataTypes.FLOAT} ,
        CostPerConversion : {type: DataTypes.FLOAT} ,
        Ctr : {type: DataTypes.STRING} ,
        CurrencyCode : {type: DataTypes.STRING} ,
        CustomParameters : {type: DataTypes.STRING},
        DeliveredMatchType : {type: DataTypes.STRING} ,
        DestinationUrl : {type: DataTypes.STRING},
        DeviceOS : {type: DataTypes.STRING} ,
        DeviceType : {type: DataTypes.STRING} ,
        DisplayUrl : {type: DataTypes.STRING},
        FinalAppUrl : {type: DataTypes.STRING},
        FinalMobileUrl : {type: DataTypes.STRING},
        FinalUrl : {type: DataTypes.STRING},
        Headline : {type: DataTypes.STRING},
        Impressions : {type: DataTypes.INTEGER} ,
        Language : {type: DataTypes.STRING} ,
        LongHeadline : {type: DataTypes.STRING},
        Network : {type: DataTypes.STRING} ,
        Path1 : {type: DataTypes.STRING} ,
        Path2 : {type: DataTypes.STRING} ,
        ReturnOnAdSpend : {type: DataTypes.FLOAT} ,
        Revenue : {type: DataTypes.FLOAT} ,
        RevenuePerAssist : {type: DataTypes.FLOAT} ,
        RevenuePerConversion : {type: DataTypes.FLOAT} ,
        Spend : {type: DataTypes.FLOAT} ,
        TimePeriod : {type: DataTypes.STRING} ,
        TitlePart1 : {type: DataTypes.STRING} ,
        TitlePart2 : {type: DataTypes.STRING} ,
        TopVsOther : {type: DataTypes.STRING} ,
        //TrackingTemplate : {type: DataTypes.STRING}
    }, { freezeTableName: true });
    AdPerformanceReportRequest.associate = models => {}
    return AdPerformanceReportRequest;
};